require('user.config')
require('user.plugins')
require('user.theme')
require('user.statusbar')
require('user.syntax')
require('user.title')
require('user.events')
require('user.hotkeys')
require('user.terminal')
require('user.session')
require('user.startup.telescope')
require('user.ssession.init')

-- plugins
require('user.nerdtree')
require('user.angular')
require('user.treesitter')
require('user.coc')
require('user.echodoc')
require('user.explorer')
require('user.nerdcommenter')
require('user.telescope')
require('user.tagbar')
require('user.copilot')
require('user.dashboard')
require('user.gitsigns')
