require('user.config')
require('user.plugins')
require('user.statusbar')
require('user.syntax')
require('user.title')
require('user.events')
require('user.hotkeys')
require('user.toggleterm')
-- require('user.startup.telescope')

require('user.git')

-- plugins
require('user.mason')
require('user.lsp.init')
require('user.cmp')
require('user.nvimtree')
require('user.treesitter')
require('user.echodoc')
require('user.comment')
require('user.telescope.init')
require('user.dashboard')
require('user.gitsigns')
require('user.theme')
require('user.autopairs')
require('user.symbols')
require('user.illuminate')
require('user.tmux')
require('user.autosession')
require("user.mediafiles")

require("user.grep")
