vim.opt.clipboard = "unnamedplus"
vim.opt.modifiable = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cmdheight = 2
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.scrolloff = 5
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.breakindent = true
vim.opt.mouse = "a"
vim.opt.shortmess = vim.opt.shortmess + "OF"
vim.opt.laststatus = 3
vim.opt.wrap = false
vim.opt.updatetime = 1000 -- faster cursor hold event
vim.opt.swapfile = false
vim.opt.ignorecase = true

vim.opt.guifont = {"CaskaydiaCove Nerd Font", ":h12"}
